# Generated by Django 5.2.7 on 2025-10-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('InventarioView', 'Permiso para ver el inventario'), ('CrearProductoView', 'Permiso para crear productos'), ('EditarProductoView', 'Permiso para editar productos'), ('EliminarProductoView', 'Permiso para eliminar productos')]},
        ),
    ]
